using System.Linq;
using Xunit;

namespace SkathIO.Rogue.Validation.FluentValidation.Generator.Tests;

/// <summary>
/// Snapshot-style tests that verify the shape of generated source code from
/// <c>RegistrationEmitter</c>. Mirrors <c>SkathIO.Rogue.Generator.Tests/EmissionTests.cs</c>'s own
/// doc comment: these do NOT use Verify.Xunit golden files — they use targeted string assertions
/// (exact patterns that must appear, forbidden patterns that must not appear).
/// </summary>
public sealed class EmissionTests
{
    private const string SingleValidatorSource = @"
using FluentValidation;

public class CreateOrderCommand
{
    public string Name { get; set; } = """";
}

public class CreateOrderCommandValidator : AbstractValidator<CreateOrderCommand>
{
    public CreateOrderCommandValidator()
        => RuleFor(x => x.Name).NotEmpty();
}";

    private const string TwoValidatorsOneRequestTypeSource = @"
using FluentValidation;

public class CreateOrderCommand
{
    public string Name { get; set; } = """";
}

public class CreateOrderCommandValidatorA : AbstractValidator<CreateOrderCommand>
{
    public CreateOrderCommandValidatorA()
        => RuleFor(x => x.Name).NotEmpty();
}

public class CreateOrderCommandValidatorB : AbstractValidator<CreateOrderCommand>
{
    public CreateOrderCommandValidatorB()
        => RuleFor(x => x.Name).MaximumLength(100);
}";

    private static string RegistrationText(string source) =>
        GeneratorTestHelper.RunGeneratorAndAssertClean(source)
            .Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueFluentValidationServiceCollectionExtensions.g.cs")
            .SourceText.ToString();

    private static string ModuleInitText(string source) =>
        GeneratorTestHelper.RunGeneratorAndAssertClean(source)
            .Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueFluentValidationModuleInit.g.cs")
            .SourceText.ToString();

    // ── Empty input ───────────────────────────────────────────────────────────────────

    [Fact]
    public void EmptyInput_GeneratorDoesNotThrow()
    {
        const string source = "// empty";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        Assert.All(result.Results, r => Assert.Null(r.Exception));
    }

    [Fact]
    public void EmptyInput_EmitsBothSourceFiles()
    {
        // Both files are ALWAYS emitted (stable hint names), even for a zero-validator compilation —
        // mirrors the core generator's RogueGeneratedRegistration/RogueModuleInit shape.
        const string source = "// empty";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        Assert.Contains(sources, s => s.HintName == "RogueFluentValidationServiceCollectionExtensions.g.cs");
        Assert.Contains(sources, s => s.HintName == "RogueFluentValidationModuleInit.g.cs");
    }

    // ── Auto-generated header ─────────────────────────────────────────────────────────

    [Fact]
    public void AllEmittedFiles_HaveAutoGeneratedHeader()
    {
        const string source = "// empty";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        foreach (var s in sources)
        {
            var text = s.SourceText.ToString();
            Assert.Contains("// <auto-generated/>", text);
            Assert.Contains("#nullable enable", text);
        }
    }

    // ── Registration content ──────────────────────────────────────────────────────────

    [Fact]
    public void SingleValidator_RegistrationContainsExpectedTryAddEnumerable()
    {
        var text = RegistrationText(SingleValidatorSource);

        Assert.Contains("namespace SkathIO.Rogue.Validation.FluentValidation.Generated", text);
        Assert.Contains("internal static class RogueFluentValidationRegistration", text);
        Assert.Contains("internal static void Register(", text);

        // D4/R5: TryAddEnumerable — never plain TryAdd.
        Assert.Contains(
            "ServiceCollectionDescriptorExtensions.TryAddEnumerable(services, "
            + "global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe("
            + "typeof(global::FluentValidation.IValidator<global::CreateOrderCommand>), "
            + "typeof(global::CreateOrderCommandValidator), "
            + "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped));",
            text);

        // D4: never options.Lifetime for validator registrations.
        Assert.DoesNotContain("options.Lifetime", text);
    }

    [Fact]
    public void TwoValidators_ForSameRequestType_BothRegistrationsEmitted()
    {
        var text = RegistrationText(TwoValidatorsOneRequestTypeSource);

        Assert.Contains(
            "typeof(global::FluentValidation.IValidator<global::CreateOrderCommand>), "
            + "typeof(global::CreateOrderCommandValidatorA), "
            + "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped));",
            text);
        Assert.Contains(
            "typeof(global::FluentValidation.IValidator<global::CreateOrderCommand>), "
            + "typeof(global::CreateOrderCommandValidatorB), "
            + "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped));",
            text);

        // Both go through TryAddEnumerable, not single-registration TryAdd (R5/D4).
        int enumerableCount = text.Split(new[] { "TryAddEnumerable" }, System.StringSplitOptions.None).Length - 1;
        Assert.Equal(2, enumerableCount);
    }

    [Fact]
    public void ZeroValidators_RegistrationClassStillEmitted_WithEmptyBody()
    {
        // The Register method is ALWAYS emitted (even with an empty body) — mirrors the core
        // generator's RogueGeneratedRegistration always existing so AddRogue's bridge invocation
        // always has a valid registrar to call, whether or not it was ever appended.
        const string source = "// empty";
        var text = RegistrationText(source);

        Assert.Contains("internal static class RogueFluentValidationRegistration", text);
        Assert.Contains("internal static void Register(", text);
        Assert.DoesNotContain("TryAddEnumerable", text);
    }

    [Fact]
    public void NamespacedValidator_RegistrationUsesFullyQualifiedNames()
    {
        const string source = @"
using FluentValidation;

namespace MyApp.Orders
{
    public class CreateOrderCommand
    {
        public string Name { get; set; } = """";
    }

    public class CreateOrderCommandValidator : AbstractValidator<CreateOrderCommand>
    {
        public CreateOrderCommandValidator()
            => RuleFor(x => x.Name).NotEmpty();
    }
}";
        var text = RegistrationText(source);

        Assert.Contains(
            "typeof(global::FluentValidation.IValidator<global::MyApp.Orders.CreateOrderCommand>), "
            + "typeof(global::MyApp.Orders.CreateOrderCommandValidator), "
            + "global::Microsoft.Extensions.DependencyInjection.ServiceLifetime.Scoped));",
            text);
    }

    // ── Module-init bridge ──────────────────────────────────────────────────────────────

    [Fact]
    public void ModuleInit_WiresBridgeToFluentValidationRegistration()
    {
        var text = ModuleInitText(SingleValidatorSource);

        Assert.Contains("#if !NETSTANDARD2_0", text);
        Assert.Contains("#endif", text);
        Assert.Contains("[global::System.Runtime.CompilerServices.ModuleInitializer]", text);

        // Appends via the public, non-obsolete Register(...) entry point — a second, independent
        // registrar on the same append-only bridge the core generator's own module init also uses.
        Assert.Contains("global::SkathIO.Rogue.RogueRegistrationBridge.Register(", text);
        Assert.Contains(
            "global::SkathIO.Rogue.Validation.FluentValidation.Generated.RogueFluentValidationRegistration.Register(svc, opts)",
            text);
    }

    [Fact]
    public void ModuleInit_SuppressedForZeroValidatorCompilation()
    {
        const string source = "// empty";
        var text = ModuleInitText(source);

        // The file is still emitted (stable hint name), but carries no initializer/bridge call —
        // full suppression proof lives in SuppressionTests.cs.
        Assert.DoesNotContain("[global::System.Runtime.CompilerServices.ModuleInitializer]", text);
        Assert.DoesNotContain("RogueRegistrationBridge", text);
    }

    // ── NFR-SEC-1-equivalent: no reflection on the emission path ───────────────────────

    [Fact]
    public void AllEmittedSources_ContainNoReflectionApis()
    {
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(TwoValidatorsOneRequestTypeSource);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        foreach (var s in sources)
        {
            var text = s.SourceText.ToString();
            Assert.DoesNotContain("MakeGenericMethod", text);
            Assert.DoesNotContain("Activator.CreateInstance", text);
            Assert.DoesNotContain("Assembly.GetTypes", text);
            Assert.DoesNotContain("AppDomain.GetAssemblies", text);
        }
    }
}
