using System.Text;

namespace SkathIO.Rogue.SourceGenerator;

/// <summary>
/// Simple indented string builder for emitting C# source. Not thread-safe; one writer per emitter call.
/// </summary>
internal sealed class CodeWriter
{
    private readonly StringBuilder _sb = new StringBuilder();
    private int _indent;
    private const string IndentStr = "    ";

    internal void Line(string text = "")
    {
        if (text.Length == 0) { _sb.AppendLine(); return; }
        for (int i = 0; i < _indent; i++) _sb.Append(IndentStr);
        _sb.AppendLine(text);
    }

    internal void Open(string header) { Line(header); Line("{"); _indent++; }
    internal void Close(string suffix = "") { _indent--; Line("}" + suffix); }
    internal void Indent() => _indent++;
    internal void Dedent() => _indent--;

    internal static string Header =>
        "// <auto-generated/>\n// Do not edit manually. Regenerated by SkathIO.Rogue source generator.\n#nullable enable\n";

    public override string ToString()
    {
        System.Diagnostics.Debug.Assert(_indent == 0, $"CodeWriter indent imbalance: {_indent} open blocks remain");
        return _sb.ToString();
    }
}
