using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using SkathIO.Rogue.Compatibility;
using SkathIO.Rogue.MediatR;

namespace SkathIO.Rogue.MediatR.Tests;

// ── Forwarding wrapper for the "drop-in alias" proof ──────────────────────────
//
// SkathIO.Rogue.MediatR.Compatibility.ISender/IMediator/IPublisher declare zero new members over
// their core SkathIO.Rogue counterparts (see each file's own "forwarding alias" comment), but no
// concrete type in the shim implements them — Mediator.cs's sealed Mediator class implements only
// the core SkathIO.Rogue.IMediator, not the adapter's Compatibility.IMediator. Nothing therefore
// registers Compatibility.IMediator/ISender in DI automatically; a consumer typing a field/ctor
// parameter as the adapter interface must forward it themselves. This is the natural, minimal way to
// do that — delegate every member to the core IMediator resolved from the same scope. Used by
// MediatRCompatTests to prove dispatch behaves identically through either interface, without
// asserting a false reference-equality claim (the wrapper is necessarily a distinct object from the
// core Mediator instance it wraps — <see cref="Inner"/> exposes that instance so the test can assert
// it is the SAME core registration).
internal sealed class ForwardingCompatMediator : SkathIO.Rogue.Compatibility.IMediator
{
    public global::SkathIO.Rogue.IMediator Inner { get; }

    public ForwardingCompatMediator(global::SkathIO.Rogue.IMediator inner) => Inner = inner;

    public ValueTask Send(global::SkathIO.Rogue.ICommand command, CancellationToken cancellationToken = default)
        => Inner.Send(command, cancellationToken);

    public ValueTask<TResponse> Send<TResponse>(global::SkathIO.Rogue.ICommand<TResponse> command, CancellationToken cancellationToken = default)
        => Inner.Send(command, cancellationToken);

    public ValueTask<TResponse> Send<TResponse>(global::SkathIO.Rogue.IQuery<TResponse> query, CancellationToken cancellationToken = default)
        => Inner.Send(query, cancellationToken);

    public ValueTask<object?> Send(object request, CancellationToken cancellationToken = default)
        => Inner.Send(request, cancellationToken);

    public IAsyncEnumerable<TItem> CreateStream<TItem>(global::SkathIO.Rogue.IStreamQuery<TItem> query, CancellationToken cancellationToken = default)
        => Inner.CreateStream(query, cancellationToken);

    public ValueTask Publish(global::SkathIO.Rogue.IEvent @event, CancellationToken cancellationToken = default)
        => Inner.Publish(@event, cancellationToken);

    public ValueTask Publish(object @event, CancellationToken cancellationToken = default)
        => Inner.Publish(@event, cancellationToken);
}

// ── Call tracker ─────────────────────────────────────────────────────────────
//
// Handlers are constructed by the DI container (TryAddTransient<THandler, THandler>, generated by
// RogueGenerator), so proving a handler actually ran requires an injected collaborator rather than
// static state — this mirrors the "shared tracker" pattern other suites in this repo use to assert
// fan-out, without the cross-test flakiness a static/shared-process field would risk.

/// <summary>Records which handlers ran, in order, for assertions.</summary>
public interface ICallTracker
{
    void RecordCall(string name);
    IReadOnlyList<string> Calls { get; }
}

/// <summary>Registered Scoped per test's own <c>ServiceCollection</c> — no cross-test sharing.</summary>
public sealed class CallTracker : ICallTracker
{
    private readonly List<string> _calls = new();
    public IReadOnlyList<string> Calls => _calls;
    public void RecordCall(string name) => _calls.Add(name);
}

// ── 1. Adapter command (unmarked IRequest<T>) → maps to ICommand<T> per F8 ────

public sealed class CreateOrderRequest : IRequest<string>
{
    public string Name { get; init; } = "";
}

public sealed class CreateOrderRequestHandler : IRequestHandler<CreateOrderRequest, string>
{
    public ValueTask<string> Handle(CreateOrderRequest request, CancellationToken cancellationToken)
        => new("created:" + request.Name);
}

// ── 2. [MapAsQuery]-marked adapter command → maps to IQuery<T> per F8 ─────────

[MapAsQuery]
public sealed class GetOrderRequest : IRequest<string>
{
    public string OrderId { get; init; } = "";
}

public sealed class GetOrderRequestHandler : IRequestHandler<GetOrderRequest, string>
{
    public ValueTask<string> Handle(GetOrderRequest request, CancellationToken cancellationToken)
        => new("fetched:" + request.OrderId);
}

// ── 3. Void adapter command (no response) ─────────────────────────────────────

public sealed class PingRequest : IRequest { }

public sealed class PingRequestHandler : IRequestHandler<PingRequest>
{
    private readonly ICallTracker _tracker;
    public PingRequestHandler(ICallTracker tracker) => _tracker = tracker;

    public ValueTask Handle(PingRequest request, CancellationToken cancellationToken)
    {
        _tracker.RecordCall("Ping");
        return default;
    }
}

// ── 4. Notification with 2 handlers ───────────────────────────────────────────

public sealed class OrderCreatedNotification : INotification
{
    public string OrderId { get; init; } = "";
}

public sealed class FirstOrderCreatedHandler : INotificationHandler<OrderCreatedNotification>
{
    private readonly ICallTracker _tracker;
    public FirstOrderCreatedHandler(ICallTracker tracker) => _tracker = tracker;

    public ValueTask Handle(OrderCreatedNotification notification, CancellationToken cancellationToken)
    {
        _tracker.RecordCall("First:" + notification.OrderId);
        return default;
    }
}

public sealed class SecondOrderCreatedHandler : INotificationHandler<OrderCreatedNotification>
{
    private readonly ICallTracker _tracker;
    public SecondOrderCreatedHandler(ICallTracker tracker) => _tracker = tracker;

    public ValueTask Handle(OrderCreatedNotification notification, CancellationToken cancellationToken)
    {
        _tracker.RecordCall("Second:" + notification.OrderId);
        return default;
    }
}
