using System.Linq;
using System.Reflection;
using Xunit;

namespace SkathIO.Rogue.Generator.Tests;

/// <summary>
/// Snapshot-style tests that verify the shape of generated source code from the emitters.
/// These do NOT use Verify golden files — they use targeted string assertions (exact patterns
/// that must appear, forbidden patterns that must not appear). The assertions cover structural
/// correctness and the NFR-SEC-1 / NFR-PERF-3 code-shape gates from the plan.
/// </summary>
public sealed class EmissionTests
{
    // ── Empty input ───────────────────────────────────────────────────────────────────

    [Fact]
    public void EmptyInput_GeneratorDoesNotThrow()
    {
        const string source = "// empty";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        Assert.All(result.Results, r => Assert.Null(r.Exception));
    }

    [Fact]
    public void EmptyInput_EmitsThreeSourceFiles()
    {
        // Even with no handlers, the generator emits the three partial stubs so the
        // partial method is satisfied.
        const string source = "// empty";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        Assert.Contains(sources, s => s.HintName == "RogueDispatcher.g.cs");
        Assert.Contains(sources, s => s.HintName == "RogueServiceCollectionExtensions.g.cs");
        Assert.Contains(sources, s => s.HintName == "RoguePipelineInspector.g.cs");
    }

    // ── Module-init bridge (PD-15 / PD-16) ─────────────────────────────────────────────

    [Fact]
    public void ModuleInit_WiresBridgeToGeneratedRegistration()
    {
        // PD-15: the consumer-compilation module initializer assigns the public
        // RogueRegistrationBridge.GeneratedRegistrar delegate so the DLL's AddRogue reaches the
        // consumer's populated RogueGeneratedRegistration.Register. Emitted even with no handlers.
        const string source = "// empty";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        var moduleInit = sources.First(s => s.HintName == "RogueModuleInit.g.cs");
        var text = moduleInit.SourceText.ToString();

        // net5+ only — ns2.0 has no ModuleInitializer
        Assert.Contains("#if !NETSTANDARD2_0", text);
        Assert.Contains("#endif", text);
        Assert.Contains("[global::System.Runtime.CompilerServices.ModuleInitializer]", text);

        // Assigns the public bridge delegate to the generated Register method (PD-16: bridge is public)
        Assert.Contains("global::SkathIO.Rogue.RogueRegistrationBridge.GeneratedRegistrar", text);
        Assert.Contains("global::SkathIO.Rogue.Generated.RogueGeneratedRegistration.Register(svc, opts)", text);
    }

    // ── Auto-generated header ─────────────────────────────────────────────────────────

    [Fact]
    public void AllEmittedFiles_HaveAutoGeneratedHeader()
    {
        const string source = "// empty";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        foreach (var s in sources)
        {
            var text = s.SourceText.ToString();
            Assert.Contains("// <auto-generated/>", text);
            Assert.Contains("#nullable enable", text);
        }
    }

    // ── Single request handler ────────────────────────────────────────────────────────

    [Fact]
    public void SingleHandler_DispatcherContains_PerRequestSendMethod()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class Ping : IRequest<string> { }
public class PingHandler : IRequestHandler<Ping, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(Ping request, System.Threading.CancellationToken ct) => ValueTask.FromResult(""pong"");
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        var dispatcher = sources.First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Per-request method named with safe name of the request FQN
        Assert.Contains("Send_Ping", text);

        // Generic Send<TResponse> override
        Assert.Contains("public override", text);
        Assert.Contains("Send<TResponse>", text);

        // PipelineExecutor used (no MakeGenericMethod)
        Assert.Contains("global::SkathIO.Rogue.PipelineExecutor", text);

        // NFR-SEC-1: no reflection-emit APIs in generated code
        Assert.DoesNotContain("MakeGenericMethod", text);
        Assert.DoesNotContain("Activator.CreateInstance", text);
        Assert.DoesNotContain("Assembly.GetTypes", text);
        Assert.DoesNotContain("AppDomain.GetAssemblies", text);

        // global:: prefix on all type references
        Assert.DoesNotContain("SkathIO.Rogue.PipelineExecutor", text.Replace("global::SkathIO.Rogue.PipelineExecutor", ""));
    }

    [Fact]
    public void SingleHandler_RegistrationContains_HandlerServiceDescriptor()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class Ping : IRequest<string> { }
public class PingHandler : IRequestHandler<Ping, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(Ping request, System.Threading.CancellationToken ct) => ValueTask.FromResult(""pong"");
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        var reg = sources.First(s => s.HintName == "RogueServiceCollectionExtensions.g.cs");
        var text = reg.SourceText.ToString();

        // PD-14: standalone registration class with a Register method (replaces the
        // cross-assembly partial method AddGeneratedRogue).
        Assert.Contains("namespace SkathIO.Rogue.Generated", text);
        Assert.Contains("internal static class RogueGeneratedRegistration", text);
        Assert.Contains("internal static void Register(", text);

        // Handler registered
        Assert.Contains("PingHandler", text);

        // Generated dispatcher subclass registered as the RogueDispatcher service
        Assert.Contains("global::SkathIO.Rogue.RogueDispatcher, global::SkathIO.Rogue.Generated.RogueDispatcherImpl", text);

        // IRoguePipelineInspector registered
        Assert.Contains("IRoguePipelineInspector", text);

        // NFR-PERF-3: no assembly scanning
        Assert.DoesNotContain("Assembly.GetTypes", text);
        Assert.DoesNotContain("GetAssemblies", text);
    }

    [Fact]
    public void SingleHandler_SendOverride_HasSwitchOnRequestType()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class Ping : IRequest<string> { }
public class PingHandler : IRequestHandler<Ping, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(Ping request, System.Threading.CancellationToken ct) => ValueTask.FromResult(""pong"");
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Switch on request type for the generic override
        Assert.Contains("switch (request)", text);
        Assert.Contains("case global::Ping", text);
        Assert.Contains("RogueUnregisteredRequestException", text);
    }

    // ── Void-path handler (ICommand) ──────────────────────────────────────────────────

    [Fact]
    public void VoidPathHandler_DispatcherHandlesUnitWrapping()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class DeleteUser : ICommand { }
public class DeleteUserHandler : ICommandHandler<DeleteUser>
{
#if NETSTANDARD2_0
    public ValueTask<Unit> Handle(DeleteUser request, System.Threading.CancellationToken ct) => Unit.Task;
#else
    public ValueTask Handle(DeleteUser request, System.Threading.CancellationToken ct) => ValueTask.CompletedTask;
#endif
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Void-path emitted
        Assert.Contains("Send_DeleteUser", text);

        // AwaitVoidThenUnit helper present
        Assert.Contains("AwaitVoidThenUnit", text);

        // Unit.Task used for sync-completing fast path
        Assert.Contains("Unit.Task", text);
    }

    // ── Pipeline behaviors ────────────────────────────────────────────────────────────

    [Fact]
    public void OpenBehavior_RegistrationContains_ClosedConstruction()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
public class GetUser : IRequest<string> { }
public class GetUserHandler : IRequestHandler<GetUser, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(GetUser request, System.Threading.CancellationToken ct) => ValueTask.FromResult(""user"");
}
public class LoggingBehavior<TReq, TRes> : IPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public ValueTask<TRes> Handle(TReq request, RequestHandlerDelegate<TRes> next, System.Threading.CancellationToken ct) => next();
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var reg = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueServiceCollectionExtensions.g.cs");
        var text = reg.SourceText.ToString();

        // Closed construction of the open behavior for this specific request type
        Assert.Contains("LoggingBehavior<global::GetUser", text);

        // IReadOnlyList<IPipelineBehavior<...>> factory registered for the dispatcher fast path
        Assert.Contains("IReadOnlyList<global::SkathIO.Rogue.IPipelineBehavior<global::GetUser", text);
    }

    // ── Notification handler ──────────────────────────────────────────────────────────

    [Fact]
    public void NotificationHandler_EmitsPublishOverrideWithSwitch()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class UserCreated : INotification { }
public class UserCreatedHandler : INotificationHandler<UserCreated>
{
#if NETSTANDARD2_0
    public ValueTask<Unit> Handle(UserCreated n, System.Threading.CancellationToken ct) => Unit.Task;
#else
    public ValueTask Handle(UserCreated n, System.Threading.CancellationToken ct) => ValueTask.CompletedTask;
#endif
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Publish method override present
        Assert.Contains("Publish(", text);

        // Per-notification dispatch method
        Assert.Contains("Publish_UserCreated", text);

        // NotificationHandlerExecutor used
        Assert.Contains("NotificationHandlerExecutor", text);
    }

    // ── Pipeline inspector ────────────────────────────────────────────────────────────

    [Fact]
    public void Inspector_EmittedWithIRoguePipelineInspectorInterface()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class Cmd : ICommand { }
public class CmdHandler : ICommandHandler<Cmd>
{
#if NETSTANDARD2_0
    public ValueTask<Unit> Handle(Cmd request, System.Threading.CancellationToken ct) => Unit.Task;
#else
    public ValueTask Handle(Cmd request, System.Threading.CancellationToken ct) => ValueTask.CompletedTask;
#endif
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        var inspector = sources.First(s => s.HintName == "RoguePipelineInspector.g.cs");
        var text = inspector.SourceText.ToString();

        // Implements the inspector interface
        Assert.Contains("IRoguePipelineInspector", text);

        // GetPipeline methods present
        Assert.Contains("GetPipeline", text);

        // Namespace
        Assert.Contains("namespace SkathIO.Rogue.Generated", text);
    }

    [Fact]
    public void Inspector_WithBehaviors_ContainsBehaviorInfoEntries()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class GetOrder : IRequest<string> { }
public class GetOrderHandler : IRequestHandler<GetOrder, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(GetOrder request, System.Threading.CancellationToken ct) => ValueTask.FromResult(""order"");
}
public class TracingBehavior<TReq, TRes> : IPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public ValueTask<TRes> Handle(TReq request, RequestHandlerDelegate<TRes> next, System.Threading.CancellationToken ct) => next();
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var inspector = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RoguePipelineInspector.g.cs");
        var text = inspector.SourceText.ToString();

        // BehaviorInfo entries for the registered behavior
        Assert.Contains("BehaviorInfo", text);
        Assert.Contains("TracingBehavior", text);
        Assert.Contains("open-generic", text);
    }

    // ── Phase 4.2.1: stream pipeline behavior weaving (FR-23) ─────────────────────────

    [Fact]
    public void StreamBehavior_RegistrationContains_StreamBehaviorList()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Collections.Generic;
using System.Threading;
public class Tick : IStreamRequest<int> { }
public class TickHandler : IStreamRequestHandler<Tick, int>
{
    public async IAsyncEnumerable<int> Handle(Tick request, System.Threading.CancellationToken ct)
    {
        yield return 1;
        await System.Threading.Tasks.Task.CompletedTask;
    }
}
public class StreamLogBehavior<TReq, TRes> : IStreamPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public IAsyncEnumerable<TRes> Handle(TReq request, StreamHandlerDelegate<TRes> next, System.Threading.CancellationToken ct) => next();
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var reg = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueServiceCollectionExtensions.g.cs");
        var text = reg.SourceText.ToString();

        // Stream behavior list registered (the IsStream `continue` guard is now removed).
        Assert.Contains("IReadOnlyList<global::SkathIO.Rogue.IStreamPipelineBehavior<global::Tick, global::System.Int32>", text);

        // Closed construction of the open stream behavior for this stream request.
        Assert.Contains("StreamLogBehavior<global::Tick, global::System.Int32>", text);

        // Stream registration is net8+-only (IStreamPipelineBehavior does not exist on ns2.0).
        Assert.Contains("#if !NETSTANDARD2_0", text);
    }

    [Fact]
    public void StreamBehavior_DispatcherWeavesBehaviorFold()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Collections.Generic;
using System.Threading;
public class Tick : IStreamRequest<int> { }
public class TickHandler : IStreamRequestHandler<Tick, int>
{
    public async IAsyncEnumerable<int> Handle(Tick request, System.Threading.CancellationToken ct)
    {
        yield return 1;
        await System.Threading.Tasks.Task.CompletedTask;
    }
}
public class StreamLogBehavior<TReq, TRes> : IStreamPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public IAsyncEnumerable<TRes> Handle(TReq request, StreamHandlerDelegate<TRes> next, System.Threading.CancellationToken ct) => next();
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Closure-based fold: resolves the stream-behavior list and chains StreamHandlerDelegate.
        Assert.Contains("CreateStream_Tick", text);
        Assert.Contains("global::SkathIO.Rogue.StreamHandlerDelegate<global::System.Int32> next", text);
        Assert.Contains("behavior.Handle(request, prevNext, cancellationToken)", text);

        // The fold must NOT use the value-task struct executor or any reflection-emit on the path.
        Assert.DoesNotContain("yield foreach", text);
        Assert.DoesNotContain("MakeGenericMethod", text);
    }

    [Fact]
    public void StreamWithNoBehaviors_DispatcherStillFolds_OverEmptyList()
    {
        // Baseline regression: a stream request with zero stream behaviors must still compile and
        // resolve an (empty) behavior list — the handler is reached through the fold over Array.Empty.
        const string source = @"
using SkathIO.Rogue;
using System.Collections.Generic;
using System.Threading;
public class Tail : IStreamRequest<string> { }
public class TailHandler : IStreamRequestHandler<Tail, string>
{
    public async IAsyncEnumerable<string> Handle(Tail request, System.Threading.CancellationToken ct)
    {
        yield return ""x"";
        await System.Threading.Tasks.Task.CompletedTask;
    }
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        Assert.Contains("CreateStream_Tail", text);
        // The empty-list fallback keeps the handler reachable even with no behaviors registered.
        Assert.Contains("global::System.Array.Empty<global::SkathIO.Rogue.IStreamPipelineBehavior<global::Tail, global::System.String>>", text);
        Assert.Contains("return next();", text);
    }

    // ── Phase 4.2.1: [BehaviorOrder] ordering (PD-4 / PD-13a) ─────────────────────────

    [Fact]
    public void BehaviorOrder_PositionsLowerOrderBehaviorOutermost()
    {
        // OuterB has [BehaviorOrder(0)]; InnerB has [BehaviorOrder(10)]. Despite source order
        // declaring InnerB first, OuterB must appear first (outermost) in the emitted list.
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class GetUser : IRequest<string> { }
public class GetUserHandler : IRequestHandler<GetUser, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(GetUser request, System.Threading.CancellationToken ct) => ValueTask.FromResult(""u"");
}
[BehaviorOrder(10)]
public class InnerB<TReq, TRes> : IPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public ValueTask<TRes> Handle(TReq r, RequestHandlerDelegate<TRes> next, System.Threading.CancellationToken ct) => next();
}
[BehaviorOrder(0)]
public class OuterB<TReq, TRes> : IPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public ValueTask<TRes> Handle(TReq r, RequestHandlerDelegate<TRes> next, System.Threading.CancellationToken ct) => next();
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var reg = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueServiceCollectionExtensions.g.cs");
        var text = reg.SourceText.ToString();

        int outerIdx = text.IndexOf("OuterB<global::GetUser", System.StringComparison.Ordinal);
        int innerIdx = text.IndexOf("InnerB<global::GetUser", System.StringComparison.Ordinal);

        Assert.True(outerIdx >= 0, "OuterB closed construction must be emitted");
        Assert.True(innerIdx >= 0, "InnerB closed construction must be emitted");
        // Lower [BehaviorOrder] = outermost = emitted first in the IReadOnlyList factory.
        Assert.True(outerIdx < innerIdx, "OuterB (order 0) must precede InnerB (order 10)");
    }

    // ── Phase 4.2.1: ROGUE007 is NOT implemented (PD-17) ──────────────────────────────

    [Fact]
    public void NoEmittedSource_ReferencesRogue007()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class P : IRequest<string> { }
public class PHandler : IRequestHandler<P, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(P request, System.Threading.CancellationToken ct) => ValueTask.FromResult(""x"");
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();
        foreach (var s in sources)
        {
            Assert.DoesNotContain("ROGUE007", s.SourceText.ToString());
        }
    }

    // ── NFR-SEC-1 / NFR-PERF-3: code-shape gate ──────────────────────────────────────

    [Fact]
    public void AllEmittedSources_ContainNoReflectionEmitApis()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
public class Q1 : IRequest<int> { }
public class Q1Handler : IRequestHandler<Q1, int>
{
    public ValueTask<int> Handle(Q1 r, System.Threading.CancellationToken ct) => ValueTask.FromResult(1);
}
public class LogB<TReq, TRes> : IPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public ValueTask<TRes> Handle(TReq req, RequestHandlerDelegate<TRes> next, System.Threading.CancellationToken ct) => next();
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        foreach (var s in sources)
        {
            var text = s.SourceText.ToString();
            Assert.DoesNotContain("MakeGenericMethod", text);
            Assert.DoesNotContain("Activator.CreateInstance", text);
            Assert.DoesNotContain("Assembly.GetTypes", text);
            Assert.DoesNotContain("AppDomain.GetAssemblies", text);
            Assert.DoesNotContain("Expression.Compile", text);
        }
    }

    [Fact]
    public void AllEmittedSources_UseGlobalQualifiedNames()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class Query : IRequest<string> { }
public class QueryHandler : IRequestHandler<Query, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(Query request, System.Threading.CancellationToken ct) => ValueTask.FromResult(""result"");
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // The handler interface reference must use global:: prefix
        Assert.Contains("global::SkathIO.Rogue.IRequestHandler<", text);
        Assert.Contains("global::SkathIO.Rogue.PipelineExecutor", text);
        Assert.Contains("global::SkathIO.Rogue.Unit", text);
    }

    // 2026-06-08 release-readiness review (9.1): GetUnboundFqn built an open-generic behavior's FQN
    // from ContainingNamespace + symbol.Name alone, dropping the containing-*type* chain — so a
    // behavior nested in "Outer" emitted "global::MyApp.LoggingBehavior<...>" instead of
    // "global::MyApp.Outer.LoggingBehavior<...>", a CS0234 ("type or namespace does not exist") in
    // the consumer's compile step. RunGeneratorAndAssertCompiles is the only check that proves the
    // *emitted* closed-generic construction — not just the model string — actually resolves; a
    // string-only assertion on UnboundTypeFqn (see DiscoveryTests) could pass while the consumer
    // build still breaks if InspectorEmitter/RegistrationEmitter mis-assembled the closed FQN.
    [Fact]
    public void NestedOpenGenericBehavior_GeneratedDispatcher_CompilesCleanly()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;

public class Ping : IRequest<string> { }
public class PingHandler : IRequestHandler<Ping, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(Ping request, System.Threading.CancellationToken ct) => ValueTask.FromResult(""pong"");
}

public class Outer
{
    public class LoggingBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
        where TRequest : notnull
    {
        public ValueTask<TResponse> Handle(TRequest request, RequestHandlerDelegate<TResponse> next, System.Threading.CancellationToken cancellationToken)
            => next();
    }
}";
        // RunGeneratorAndAssertCompiles asserts zero Error-severity diagnostics on the consumer
        // source + every generated source recompiled together — the exact gate a CS0234 trips.
        var compilation = GeneratorTestHelper.RunGeneratorAndAssertCompiles(source);

        // Pin the corrected FQN shape in the emitted registration/inspector source too, so a
        // regression that re-drops "Outer" surfaces here with a precise diff, not just a CS0234.
        var generated = string.Join("\n", compilation.SyntaxTrees.Select(t => t.ToString()));
        Assert.Contains("global::Outer.LoggingBehavior<", generated);
        Assert.DoesNotContain("global::LoggingBehavior<", generated);
    }

    // ── FR-25/26/27 processor bridge (PD-29 resolution) ────────────────────────────────

    private const string ProcessorSource = @"
using System;
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class Ping : IRequest<string> { }
public class PingHandler : IRequestHandler<Ping, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(Ping request, System.Threading.CancellationToken ct) => ValueTask.FromResult(""pong"");
}
public class PrePing : IRequestPreProcessor<Ping>
{
    public ValueTask Process(Ping request, System.Threading.CancellationToken ct) => default;
}
public class PostPing : IRequestPostProcessor<Ping, string>
{
    public ValueTask Process(Ping request, string response, System.Threading.CancellationToken ct) => default;
}
public class ExHandlerPing : IRequestExceptionHandler<Ping, string, InvalidOperationException>
{
    public ValueTask Handle(Ping request, InvalidOperationException ex, RequestExceptionHandlerState<string> state, System.Threading.CancellationToken ct)
    {
        state.SetHandled(""fallback"");
        return default;
    }
}
public class ExActionPing : IRequestExceptionAction<Ping, InvalidOperationException>
{
    public ValueTask Execute(Ping request, InvalidOperationException ex, System.Threading.CancellationToken ct) => default;
}";

    // Covers: FR-25 — the generated dispatch loop resolves and invokes the pre/post processors.
    [Fact]
    public void Processors_DispatcherInvokes_PreAndPostProcessors()
    {
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(ProcessorSource);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Pre-processors are resolved as a set and awaited before the pipeline; post-processors after.
        Assert.Contains("GetServices<global::SkathIO.Rogue.IRequestPreProcessor<global::Ping>>", text);
        Assert.Contains("GetServices<global::SkathIO.Rogue.IRequestPostProcessor<global::Ping, global::System.String>>", text);
        Assert.Contains("await pre.Process(request, cancellationToken)", text);
        Assert.Contains("await postProc.Process(request, response, cancellationToken)", text);
    }

    // Covers: FR-26 — the generated dispatch loop catches exceptions, runs observe-only actions, and
    // invokes exception handlers that may supply a fallback response.
    [Fact]
    public void Processors_DispatcherInvokes_ExceptionHandlerAndAction()
    {
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(ProcessorSource);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Statically-typed `is TEx` matching — no reflection (NFR-SEC-1).
        Assert.Contains("catch (global::System.Exception ex)", text);
        Assert.Contains("ex is global::System.InvalidOperationException", text);
        Assert.Contains("new global::SkathIO.Rogue.RequestExceptionHandlerState<global::System.String>()", text);
        Assert.Contains("exHandler.Handle(request,", text);
        Assert.Contains("action.Execute(request,", text);
        Assert.Contains("if (exState.Handled)", text);
        Assert.Contains("return exState.Response!;", text);
    }

    // Covers: FR-27 — processors run through the SAME PipelineExecutor engine as behaviors (no second
    // pipeline), and NFR-SEC-1 is preserved (no reflection-heavy APIs on the dispatch path).
    [Fact]
    public void Processors_RunThroughSingleEngine_NoReflection()
    {
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(ProcessorSource);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // The behavior pipeline still runs through PipelineExecutor.Execute inside the processor wrap.
        Assert.Contains("global::SkathIO.Rogue.PipelineExecutor.Execute<global::Ping, global::System.String>", text);

        // NFR-SEC-1: no reflection-heavy APIs introduced on the generated dispatch path.
        Assert.DoesNotContain("MakeGenericMethod", text);
        Assert.DoesNotContain("Activator.CreateInstance", text);
        Assert.DoesNotContain("Expression.Compile", text);
    }

    // A request type with NO processors keeps the allocation-conscious fast path (PD-2/PD-12): a
    // direct PipelineExecutor.Execute call with no try/catch and no processor resolution.
    [Fact]
    public void NoProcessors_KeepsFastPath_NoTryCatchOrProcessorResolution()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class Plain : IRequest<string> { }
public class PlainHandler : IRequestHandler<Plain, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(Plain request, System.Threading.CancellationToken ct) => ValueTask.FromResult(""x"");
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // The Send_Plain method body must not contain processor resolution or a try/catch.
        int start = text.IndexOf("Send_Plain(global::Plain request", System.StringComparison.Ordinal);
        Assert.True(start >= 0);
        // Look at the slice that contains the Send_Plain method body (up to the next private method —
        // which, per PD-31, is the Send_Plain_WithBehaviors companion the fast path delegates to for
        // the has-behaviors case; see EmitSendWithBehaviorsMethod).
        string after = text.Substring(start);
        int nextMethod = after.IndexOf("private ", 1, System.StringComparison.Ordinal);
        string body = nextMethod > 0 ? after.Substring(0, nextMethod) : after;

        Assert.DoesNotContain("GetServices<global::SkathIO.Rogue.IRequestPreProcessor", body);
        Assert.DoesNotContain("catch (", body);

        // PD-31 (AC-C / NFR-PERF-1 closure elimination): the fast path must not build a
        // RequestHandlerDelegate or call PipelineExecutor.Execute inline — both would force a
        // display-class allocation that Roslyn would hoist to the top of THIS method (shared
        // `handler`/`request`/`cancellationToken` locals). Instead it delegates the has-behaviors
        // case to a companion method, confining that closure's scope away from the fast path.
        Assert.DoesNotContain("RequestHandlerDelegate<", body);
        Assert.DoesNotContain("global::SkathIO.Rogue.PipelineExecutor.Execute", body);
        Assert.Contains("Send_Plain_WithBehaviors(handler, request, behaviors, cancellationToken)", body);

        // The companion method must exist and be the one that actually drives PipelineExecutor.
        Assert.Contains("private static global::System.Threading.Tasks.ValueTask<global::System.String> Send_Plain_WithBehaviors(", text);
        int companionStart = text.IndexOf("Send_Plain_WithBehaviors(global::SkathIO.Rogue.IRequestHandler", System.StringComparison.Ordinal);
        Assert.True(companionStart >= 0);
        string companionBody = text.Substring(companionStart);
        Assert.Contains("global::SkathIO.Rogue.PipelineExecutor.Execute", companionBody);
    }

    // ── FR-25/26/27 compile-verification matrix (pass 2, review 2026-06-07) ─────────────
    //
    // RunGeneratorAndAssertClean only proves the generator did not throw — it does NOT prove the
    // emitted dispatcher compiles in a consumer project. These tests feed the generated source through
    // a real CSharpCompilation and assert zero Error diagnostics, across the processor-combination
    // space that string-matching alone left uncovered (which is how defects #1 and #2 shipped in
    // pass 1). Reverting either emitter fix makes the corresponding test below fail.

    // Defect #1 repro shape: an exception ACTION registered with NO matching handler and NO
    // post-processors. Pass-1 emitted `var response` inside the try but referenced it in the post-try
    // `return response;` → CS0103. This test compiles the emitted dispatcher and fails on that error.
    [Fact]
    public void Compiles_ExceptionActionOnly_NoHandler_NoPostProcessor()
    {
        const string source = @"
using System;
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class ActionOnly : IRequest<string> { }
public class ActionOnlyHandler : IRequestHandler<ActionOnly, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(ActionOnly request, System.Threading.CancellationToken ct) => ValueTask.FromResult(""r"");
}
public class ActionOnlyExAction : IRequestExceptionAction<ActionOnly, InvalidOperationException>
{
    public ValueTask Execute(ActionOnly request, InvalidOperationException ex, System.Threading.CancellationToken ct) => default;
}";
        // Compiles cleanly => `response` is declared at RunWithProcessors scope, covering both the
        // try body assignment and the post-try `return response;`.
        GeneratorTestHelper.RunGeneratorAndAssertCompiles(source);
    }

    // Defect #2 repro shape (compile half): two exception actions sharing one TEx. Pass-1 emitted two
    // `if (ex is InvalidOperationException ...)` blocks, each resolving the full action set. The
    // grouping fix collapses them to one block — assert exactly one `is` block is emitted for the
    // shared TEx, and that the result still compiles.
    [Fact]
    public void Compiles_TwoExceptionActions_SharingOneExceptionType_SingleBlock()
    {
        const string source = TwoActionsSharingTExSource;

        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Exactly ONE `if (ex is InvalidOperationException ...)` block for the shared exception type.
        int count = CountOccurrences(text, "if (ex is global::System.InvalidOperationException");
        Assert.Equal(1, count);

        // And it still compiles.
        GeneratorTestHelper.RunGeneratorAndAssertCompiles(source);
    }

    // Defect #2 repro shape (runtime half): with two actions registered for the same TEx, each action
    // must fire EXACTLY ONCE per thrown exception. Pass-1 fired each twice (4 total for 2 actions).
    // Compile-cleanliness cannot see this — only a runtime dispatch can. This test loads the generated
    // assembly, builds the DI container from the generated registration, dispatches a request that
    // throws, and asserts each action's invocation count is exactly 1.
    [Fact]
    public void Runtime_TwoExceptionActions_SharingOneExceptionType_EachFiresExactlyOnce()
    {
        var assembly = GeneratorTestHelper.EmitAndLoadAssembly(TwoActionsSharingTExSource);
        var provider = GeneratorTestHelper.BuildProviderFromGenerated(assembly);

        var senderType = typeof(SkathIO.Rogue.ISender);
        var sender = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions
            .GetRequiredService(provider, senderType);

        // Resolve the request type from the loaded assembly and create an instance.
        var requestType = assembly.GetType("Faulting", throwOnError: true)!;
        var request = System.Activator.CreateInstance(requestType)!;

        // ISender.Send<TResponse>(IRequest<TResponse>, System.Threading.CancellationToken) — close over the request's response.
        var sendMethod = senderType.GetMethods()
            .First(m => m.Name == "Send" && m.IsGenericMethodDefinition && m.GetParameters().Length == 2)
            .MakeGenericMethod(typeof(string));

        // The handler throws InvalidOperationException; no exception handler is registered, so the
        // exception propagates out of Send after the (observe-only) actions run. Await the ValueTask.
        var ex = Assert.ThrowsAny<System.Exception>(() =>
        {
            object valueTask = sendMethod.Invoke(sender, new object?[] { request, System.Threading.CancellationToken.None })!;
            // System.Threading.Tasks.ValueTask<string>.AsTask().GetAwaiter().GetResult()
            var asTask = valueTask.GetType().GetMethod("AsTask")!.Invoke(valueTask, null)!;
            ((System.Threading.Tasks.Task)asTask).GetAwaiter().GetResult();
        });

        // The two actions write their invocation counts into the shared static counter on the request
        // assembly's type. Read them back via reflection and assert each fired exactly once.
        var counterType = assembly.GetType("ActionCounter", throwOnError: true)!;
        int countA = (int)counterType.GetField("CountA", BindingFlags.Public | BindingFlags.Static)!.GetValue(null)!;
        int countB = (int)counterType.GetField("CountB", BindingFlags.Public | BindingFlags.Static)!.GetValue(null)!;

        Assert.Equal(1, countA);
        Assert.Equal(1, countB);
    }

    // The "everything" combination: pre + post + exception handler + exception action all present
    // together. The pass-1 happy path covered this string-wise; this asserts it actually compiles.
    [Fact]
    public void Compiles_AllProcessorKindsPresent_Together()
    {
        // ProcessorSource already registers one of each kind, matched to one request/response/exception.
        GeneratorTestHelper.RunGeneratorAndAssertCompiles(ProcessorSource);
    }

    // Regression: the existing single-fixture combination must keep compiling.
    [Fact]
    public void Compiles_ExistingSingleFixtureCombination()
    {
        GeneratorTestHelper.RunGeneratorAndAssertCompiles(ProcessorSource);
    }

    // Fixture: two IRequestExceptionAction implementations sharing one TEx, on a handler that throws
    // (so the catch path is exercised at runtime). The actions bump a shared static counter so the
    // runtime test can assert each fired exactly once.
    private const string TwoActionsSharingTExSource = @"
using System;
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;

public static class ActionCounter
{
    public static int CountA;
    public static int CountB;
}

public class Faulting : IRequest<string> { }

public class FaultingHandler : IRequestHandler<Faulting, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(Faulting request, System.Threading.CancellationToken ct)
        => throw new InvalidOperationException(""boom"");
}

public class ActionA : IRequestExceptionAction<Faulting, InvalidOperationException>
{
    public ValueTask Execute(Faulting request, InvalidOperationException ex, System.Threading.CancellationToken ct)
    {
        ActionCounter.CountA++;
        return default;
    }
}

public class ActionB : IRequestExceptionAction<Faulting, InvalidOperationException>
{
    public ValueTask Execute(Faulting request, InvalidOperationException ex, System.Threading.CancellationToken ct)
    {
        ActionCounter.CountB++;
        return default;
    }
}";

    // ── PD-31 / AC-C / NFR-PERF-1: end-to-end closure-elimination allocation proof ─────

    private const string PingFastPathSource = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;

public class PingRequest : IRequest<string> { }

public class PingHandler : IRequestHandler<PingRequest, string>
{
    public System.Threading.Tasks.ValueTask<string> Handle(PingRequest request, System.Threading.CancellationToken ct) => new System.Threading.Tasks.ValueTask<string>(""pong"");
}";

    /// <summary>
    /// PD-31 (AC-C / NFR-PERF-1): the no-behavior, no-processor, sync-completing dispatch path must
    /// allocate zero bytes — the prior <c>RequestHandlerDelegate&lt;TResponse&gt; handlerCall = () =&gt;
    /// handler.Handle(...)</c> lambda captured <c>handler</c>/<c>request</c>/<c>cancellationToken</c>
    /// (a per-dispatch display-class closure) on every <c>Send</c>, defeating the "0 bytes" promise.
    ///
    /// Per <c>spec.md</c> scenario 1 (PD-12), the "0 bytes" claim is specifically about the
    /// <b>concrete</b> <c>RogueDispatcher.Send_PingRequest()</c> method — NOT the polymorphic
    /// <c>ISender.Send&lt;TResponse&gt;()</c> entry point, whose <c>(object)(ValueTask&lt;TResponse&gt;)</c>
    /// generic-variance cast unavoidably boxes the returned <c>ValueTask&lt;TResponse&gt;</c> on every
    /// call (a separate, pre-existing cost of polymorphic dispatch, orthogonal to the closure PD-31
    /// removes — confirmed empirically: routing this same scenario through <c>ISender.Send&lt;string&gt;</c>
    /// measures ~80 B/call even after the fix, while the concrete method measures 0). So this test
    /// resolves the live <c>RogueDispatcher</c>, finds the private <c>Send_PingRequest</c> via
    /// reflection, and binds a genuinely non-boxing, compiled delegate to it through
    /// <see cref="MeasureConcreteSendAllocations{TRequest, TResponse}"/> — a generic helper invoked
    /// ONCE via <c>MakeGenericMethod</c> (so reflection overhead lands outside the measured loop) whose
    /// JIT-specialized body creates a statically-typed <c>Func&lt;TRequest, CancellationToken,
    /// ValueTask&lt;TResponse&gt;&gt;</c> delegate — NOT <c>MethodInfo.Invoke</c>/<c>DynamicInvoke</c>,
    /// both of which box the <c>ValueTask</c> return and the <c>CancellationToken</c> argument on every
    /// call and would swamp the measurement with harness noise (D2: loop 1000x to average out any
    /// residual tiered-JIT/GC bookkeeping noise from a single sample).
    ///
    /// Handler lifetime is pinned to Singleton (not <c>GeneratorTestHelper</c>'s/<c>RogueOptions</c>'s
    /// Transient default), which would allocate a fresh <c>PingHandler</c> on every
    /// <c>GetRequiredService&lt;IRequestHandler&lt;...&gt;&gt;</c> resolution inside
    /// <c>Send_PingRequest</c> — a real, expected, user-controlled cost of the *default* lifetime,
    /// orthogonal to the closure this fix eliminates.
    /// </summary>
    [Fact]
    public async System.Threading.Tasks.Task Send_PingRequest_NoBehaviorsSyncCompletingPath_AllocatesZeroBytes()
    {
        var assembly = GeneratorTestHelper.EmitAndLoadAssembly(PingFastPathSource);

        var anyGeneratedType = assembly.GetType("SkathIO.Rogue.Generated.RogueGeneratedRegistration", throwOnError: true)!;
        System.Runtime.CompilerServices.RuntimeHelpers.RunModuleConstructor(anyGeneratedType.Module.ModuleHandle);
        var services = new Microsoft.Extensions.DependencyInjection.ServiceCollection();
        SkathIO.Rogue.RogueServiceCollectionExtensions.AddRogue(services, o => o.Lifetime = Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton);
        var provider = Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(services);

        var dispatcher = Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions
            .GetRequiredService(provider, typeof(SkathIO.Rogue.RogueDispatcher));

        var requestType = assembly.GetType("PingRequest", throwOnError: true)!;
        var request = System.Activator.CreateInstance(requestType)!;

        var sendPingRequest = dispatcher.GetType().GetMethod(
            "Send_PingRequest",
            System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)!;

        // Invoke the generic measurer with TRequest/TResponse bound to the loaded assembly's
        // PingRequest/string — the ONE reflective call in this test, made before the measured loop.
        var measure = typeof(EmissionTests)
            .GetMethod(nameof(MeasureConcreteSendAllocations), System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)!
            .MakeGenericMethod(requestType, typeof(string));

        var task = (System.Threading.Tasks.Task<long>)measure.Invoke(null, new[] { dispatcher, sendPingRequest, request, (object)1000 })!;
        long delta = await task;

        Assert.Equal(0L, delta);
    }

    /// <summary>
    /// Generic so the JIT specializes <typeparamref name="TRequest"/>/<typeparamref name="TResponse"/>
    /// concretely — letting <c>Delegate.CreateDelegate</c> bind a compiled, non-boxing
    /// <c>Func&lt;TRequest, CancellationToken, ValueTask&lt;TResponse&gt;&gt;</c> directly to the
    /// (otherwise-private, runtime-discovered) <c>Send_&lt;Request&gt;</c> method.
    /// </summary>
    private static async System.Threading.Tasks.Task<long> MeasureConcreteSendAllocations<TRequest, TResponse>(
        object dispatcher, System.Reflection.MethodInfo sendMethod, object request, int iterations)
        where TRequest : notnull
    {
        var send = (System.Func<TRequest, System.Threading.CancellationToken, System.Threading.Tasks.ValueTask<TResponse>>)
            sendMethod.CreateDelegate(
                typeof(System.Func<TRequest, System.Threading.CancellationToken, System.Threading.Tasks.ValueTask<TResponse>>),
                dispatcher);
        var typedRequest = (TRequest)request;

        // Warm up: let tiered JIT settle on steady-state codegen before measuring (D2/D6). `await`
        // (not `.Result`/`.GetAwaiter().GetResult()`) on an already-synchronously-completed
        // ValueTask<T> takes the allocation-free fast path.
        for (int i = 0; i < iterations; i++)
        {
            var warm = send(typedRequest, System.Threading.CancellationToken.None);
            if (!warm.IsCompletedSuccessfully)
            {
                throw new System.InvalidOperationException("Expected a synchronously-completing handler for this scenario.");
            }
            _ = await warm;
        }

        long before = System.GC.GetAllocatedBytesForCurrentThread();
        for (int i = 0; i < iterations; i++)
        {
            var vt = send(typedRequest, System.Threading.CancellationToken.None);
            if (!vt.IsCompletedSuccessfully)
            {
                throw new System.InvalidOperationException("Expected a synchronously-completing handler for this scenario.");
            }
            _ = await vt;
        }
        return System.GC.GetAllocatedBytesForCurrentThread() - before;
    }

    private static int CountOccurrences(string haystack, string needle)
    {
        int count = 0;
        int idx = 0;
        while ((idx = haystack.IndexOf(needle, idx, System.StringComparison.Ordinal)) >= 0)
        {
            count++;
            idx += needle.Length;
        }
        return count;
    }
}
