using System.Linq;
using Xunit;

namespace SkathIO.Rogue.Generator.Tests;

/// <summary>
/// Snapshot-style tests that verify the shape of generated source code from the emitters.
/// These do NOT use Verify golden files — they use targeted string assertions (exact patterns
/// that must appear, forbidden patterns that must not appear). The assertions cover structural
/// correctness and the NFR-SEC-1 / NFR-PERF-3 code-shape gates from the plan.
/// </summary>
public sealed class EmissionTests
{
    // ── Empty input ───────────────────────────────────────────────────────────────────

    [Fact]
    public void EmptyInput_GeneratorDoesNotThrow()
    {
        const string source = "// empty";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        Assert.All(result.Results, r => Assert.Null(r.Exception));
    }

    [Fact]
    public void EmptyInput_EmitsThreeSourceFiles()
    {
        // Even with no handlers, the generator emits the three partial stubs so the
        // partial method is satisfied.
        const string source = "// empty";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        Assert.Contains(sources, s => s.HintName == "RogueDispatcher.g.cs");
        Assert.Contains(sources, s => s.HintName == "RogueServiceCollectionExtensions.g.cs");
        Assert.Contains(sources, s => s.HintName == "RoguePipelineInspector.g.cs");
    }

    // ── Module-init bridge (PD-15 / PD-16) ─────────────────────────────────────────────

    [Fact]
    public void ModuleInit_WiresBridgeToGeneratedRegistration()
    {
        // PD-15: the consumer-compilation module initializer assigns the public
        // RogueRegistrationBridge.GeneratedRegistrar delegate so the DLL's AddRogue reaches the
        // consumer's populated RogueGeneratedRegistration.Register. Emitted even with no handlers.
        const string source = "// empty";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        var moduleInit = sources.First(s => s.HintName == "RogueModuleInit.g.cs");
        var text = moduleInit.SourceText.ToString();

        // net5+ only — ns2.0 has no ModuleInitializer
        Assert.Contains("#if !NETSTANDARD2_0", text);
        Assert.Contains("#endif", text);
        Assert.Contains("[global::System.Runtime.CompilerServices.ModuleInitializer]", text);

        // Assigns the public bridge delegate to the generated Register method (PD-16: bridge is public)
        Assert.Contains("global::SkathIO.Rogue.RogueRegistrationBridge.GeneratedRegistrar", text);
        Assert.Contains("global::SkathIO.Rogue.Generated.RogueGeneratedRegistration.Register(svc, opts)", text);
    }

    // ── Auto-generated header ─────────────────────────────────────────────────────────

    [Fact]
    public void AllEmittedFiles_HaveAutoGeneratedHeader()
    {
        const string source = "// empty";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        foreach (var s in sources)
        {
            var text = s.SourceText.ToString();
            Assert.Contains("// <auto-generated/>", text);
            Assert.Contains("#nullable enable", text);
        }
    }

    // ── Single request handler ────────────────────────────────────────────────────────

    [Fact]
    public void SingleHandler_DispatcherContains_PerRequestSendMethod()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class Ping : IRequest<string> { }
public class PingHandler : IRequestHandler<Ping, string>
{
    public ValueTask<string> Handle(Ping request, CancellationToken ct) => ValueTask.FromResult(""pong"");
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        var dispatcher = sources.First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Per-request method named with safe name of the request FQN
        Assert.Contains("Send_Ping", text);

        // Generic Send<TResponse> override
        Assert.Contains("public override", text);
        Assert.Contains("Send<TResponse>", text);

        // PipelineExecutor used (no MakeGenericMethod)
        Assert.Contains("global::SkathIO.Rogue.PipelineExecutor", text);

        // NFR-SEC-1: no reflection-emit APIs in generated code
        Assert.DoesNotContain("MakeGenericMethod", text);
        Assert.DoesNotContain("Activator.CreateInstance", text);
        Assert.DoesNotContain("Assembly.GetTypes", text);
        Assert.DoesNotContain("AppDomain.GetAssemblies", text);

        // global:: prefix on all type references
        Assert.DoesNotContain("SkathIO.Rogue.PipelineExecutor", text.Replace("global::SkathIO.Rogue.PipelineExecutor", ""));
    }

    [Fact]
    public void SingleHandler_RegistrationContains_HandlerServiceDescriptor()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class Ping : IRequest<string> { }
public class PingHandler : IRequestHandler<Ping, string>
{
    public ValueTask<string> Handle(Ping request, CancellationToken ct) => ValueTask.FromResult(""pong"");
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        var reg = sources.First(s => s.HintName == "RogueServiceCollectionExtensions.g.cs");
        var text = reg.SourceText.ToString();

        // PD-14: standalone registration class with a Register method (replaces the
        // cross-assembly partial method AddGeneratedRogue).
        Assert.Contains("namespace SkathIO.Rogue.Generated", text);
        Assert.Contains("internal static class RogueGeneratedRegistration", text);
        Assert.Contains("internal static void Register(", text);

        // Handler registered
        Assert.Contains("PingHandler", text);

        // Generated dispatcher subclass registered as the RogueDispatcher service
        Assert.Contains("global::SkathIO.Rogue.RogueDispatcher, global::SkathIO.Rogue.Generated.RogueDispatcherImpl", text);

        // IRoguePipelineInspector registered
        Assert.Contains("IRoguePipelineInspector", text);

        // NFR-PERF-3: no assembly scanning
        Assert.DoesNotContain("Assembly.GetTypes", text);
        Assert.DoesNotContain("GetAssemblies", text);
    }

    [Fact]
    public void SingleHandler_SendOverride_HasSwitchOnRequestType()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class Ping : IRequest<string> { }
public class PingHandler : IRequestHandler<Ping, string>
{
    public ValueTask<string> Handle(Ping request, CancellationToken ct) => ValueTask.FromResult(""pong"");
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Switch on request type for the generic override
        Assert.Contains("switch (request)", text);
        Assert.Contains("case global::Ping", text);
        Assert.Contains("RogueUnregisteredRequestException", text);
    }

    // ── Void-path handler (ICommand) ──────────────────────────────────────────────────

    [Fact]
    public void VoidPathHandler_DispatcherHandlesUnitWrapping()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class DeleteUser : ICommand { }
public class DeleteUserHandler : ICommandHandler<DeleteUser>
{
#if NETSTANDARD2_0
    public ValueTask<Unit> Handle(DeleteUser request, CancellationToken ct) => Unit.Task;
#else
    public ValueTask Handle(DeleteUser request, CancellationToken ct) => ValueTask.CompletedTask;
#endif
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Void-path emitted
        Assert.Contains("Send_DeleteUser", text);

        // AwaitVoidThenUnit helper present
        Assert.Contains("AwaitVoidThenUnit", text);

        // Unit.Task used for sync-completing fast path
        Assert.Contains("Unit.Task", text);
    }

    // ── Pipeline behaviors ────────────────────────────────────────────────────────────

    [Fact]
    public void OpenBehavior_RegistrationContains_ClosedConstruction()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
public class GetUser : IRequest<string> { }
public class GetUserHandler : IRequestHandler<GetUser, string>
{
    public ValueTask<string> Handle(GetUser request, CancellationToken ct) => ValueTask.FromResult(""user"");
}
public class LoggingBehavior<TReq, TRes> : IPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public ValueTask<TRes> Handle(TReq request, RequestHandlerDelegate<TRes> next, CancellationToken ct) => next();
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var reg = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueServiceCollectionExtensions.g.cs");
        var text = reg.SourceText.ToString();

        // Closed construction of the open behavior for this specific request type
        Assert.Contains("LoggingBehavior<global::GetUser", text);

        // IReadOnlyList<IPipelineBehavior<...>> factory registered for the dispatcher fast path
        Assert.Contains("IReadOnlyList<global::SkathIO.Rogue.IPipelineBehavior<global::GetUser", text);
    }

    // ── Notification handler ──────────────────────────────────────────────────────────

    [Fact]
    public void NotificationHandler_EmitsPublishOverrideWithSwitch()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class UserCreated : INotification { }
public class UserCreatedHandler : INotificationHandler<UserCreated>
{
#if NETSTANDARD2_0
    public ValueTask<Unit> Handle(UserCreated n, CancellationToken ct) => Unit.Task;
#else
    public ValueTask Handle(UserCreated n, CancellationToken ct) => ValueTask.CompletedTask;
#endif
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Publish method override present
        Assert.Contains("Publish(", text);

        // Per-notification dispatch method
        Assert.Contains("Publish_UserCreated", text);

        // NotificationHandlerExecutor used
        Assert.Contains("NotificationHandlerExecutor", text);
    }

    // ── Pipeline inspector ────────────────────────────────────────────────────────────

    [Fact]
    public void Inspector_EmittedWithIRoguePipelineInspectorInterface()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class Cmd : ICommand { }
public class CmdHandler : ICommandHandler<Cmd>
{
#if NETSTANDARD2_0
    public ValueTask<Unit> Handle(Cmd request, CancellationToken ct) => Unit.Task;
#else
    public ValueTask Handle(Cmd request, CancellationToken ct) => ValueTask.CompletedTask;
#endif
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        var inspector = sources.First(s => s.HintName == "RoguePipelineInspector.g.cs");
        var text = inspector.SourceText.ToString();

        // Implements the inspector interface
        Assert.Contains("IRoguePipelineInspector", text);

        // GetPipeline methods present
        Assert.Contains("GetPipeline", text);

        // Namespace
        Assert.Contains("namespace SkathIO.Rogue.Generated", text);
    }

    [Fact]
    public void Inspector_WithBehaviors_ContainsBehaviorInfoEntries()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class GetOrder : IRequest<string> { }
public class GetOrderHandler : IRequestHandler<GetOrder, string>
{
    public ValueTask<string> Handle(GetOrder request, CancellationToken ct) => ValueTask.FromResult(""order"");
}
public class TracingBehavior<TReq, TRes> : IPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public ValueTask<TRes> Handle(TReq request, RequestHandlerDelegate<TRes> next, CancellationToken ct) => next();
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var inspector = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RoguePipelineInspector.g.cs");
        var text = inspector.SourceText.ToString();

        // BehaviorInfo entries for the registered behavior
        Assert.Contains("BehaviorInfo", text);
        Assert.Contains("TracingBehavior", text);
        Assert.Contains("open-generic", text);
    }

    // ── Phase 4.2.1: stream pipeline behavior weaving (FR-23) ─────────────────────────

    [Fact]
    public void StreamBehavior_RegistrationContains_StreamBehaviorList()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Collections.Generic;
using System.Threading;
public class Tick : IStreamRequest<int> { }
public class TickHandler : IStreamRequestHandler<Tick, int>
{
    public async IAsyncEnumerable<int> Handle(Tick request, CancellationToken ct)
    {
        yield return 1;
        await System.Threading.Tasks.Task.CompletedTask;
    }
}
public class StreamLogBehavior<TReq, TRes> : IStreamPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public IAsyncEnumerable<TRes> Handle(TReq request, StreamHandlerDelegate<TRes> next, CancellationToken ct) => next();
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var reg = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueServiceCollectionExtensions.g.cs");
        var text = reg.SourceText.ToString();

        // Stream behavior list registered (the IsStream `continue` guard is now removed).
        Assert.Contains("IReadOnlyList<global::SkathIO.Rogue.IStreamPipelineBehavior<global::Tick, global::System.Int32>", text);

        // Closed construction of the open stream behavior for this stream request.
        Assert.Contains("StreamLogBehavior<global::Tick, global::System.Int32>", text);

        // Stream registration is net8+-only (IStreamPipelineBehavior does not exist on ns2.0).
        Assert.Contains("#if !NETSTANDARD2_0", text);
    }

    [Fact]
    public void StreamBehavior_DispatcherWeavesBehaviorFold()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Collections.Generic;
using System.Threading;
public class Tick : IStreamRequest<int> { }
public class TickHandler : IStreamRequestHandler<Tick, int>
{
    public async IAsyncEnumerable<int> Handle(Tick request, CancellationToken ct)
    {
        yield return 1;
        await System.Threading.Tasks.Task.CompletedTask;
    }
}
public class StreamLogBehavior<TReq, TRes> : IStreamPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public IAsyncEnumerable<TRes> Handle(TReq request, StreamHandlerDelegate<TRes> next, CancellationToken ct) => next();
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // Closure-based fold: resolves the stream-behavior list and chains StreamHandlerDelegate.
        Assert.Contains("CreateStream_Tick", text);
        Assert.Contains("global::SkathIO.Rogue.StreamHandlerDelegate<global::System.Int32> next", text);
        Assert.Contains("behavior.Handle(request, prevNext, cancellationToken)", text);

        // The fold must NOT use the value-task struct executor or any reflection-emit on the path.
        Assert.DoesNotContain("yield foreach", text);
        Assert.DoesNotContain("MakeGenericMethod", text);
    }

    [Fact]
    public void StreamWithNoBehaviors_DispatcherStillFolds_OverEmptyList()
    {
        // Baseline regression: a stream request with zero stream behaviors must still compile and
        // resolve an (empty) behavior list — the handler is reached through the fold over Array.Empty.
        const string source = @"
using SkathIO.Rogue;
using System.Collections.Generic;
using System.Threading;
public class Tail : IStreamRequest<string> { }
public class TailHandler : IStreamRequestHandler<Tail, string>
{
    public async IAsyncEnumerable<string> Handle(Tail request, CancellationToken ct)
    {
        yield return ""x"";
        await System.Threading.Tasks.Task.CompletedTask;
    }
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        Assert.Contains("CreateStream_Tail", text);
        // The empty-list fallback keeps the handler reachable even with no behaviors registered.
        Assert.Contains("global::System.Array.Empty<global::SkathIO.Rogue.IStreamPipelineBehavior<global::Tail, global::System.String>>", text);
        Assert.Contains("return next();", text);
    }

    // ── Phase 4.2.1: [BehaviorOrder] ordering (PD-4 / PD-13a) ─────────────────────────

    [Fact]
    public void BehaviorOrder_PositionsLowerOrderBehaviorOutermost()
    {
        // OuterB has [BehaviorOrder(0)]; InnerB has [BehaviorOrder(10)]. Despite source order
        // declaring InnerB first, OuterB must appear first (outermost) in the emitted list.
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class GetUser : IRequest<string> { }
public class GetUserHandler : IRequestHandler<GetUser, string>
{
    public ValueTask<string> Handle(GetUser request, CancellationToken ct) => ValueTask.FromResult(""u"");
}
[BehaviorOrder(10)]
public class InnerB<TReq, TRes> : IPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public ValueTask<TRes> Handle(TReq r, RequestHandlerDelegate<TRes> next, CancellationToken ct) => next();
}
[BehaviorOrder(0)]
public class OuterB<TReq, TRes> : IPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public ValueTask<TRes> Handle(TReq r, RequestHandlerDelegate<TRes> next, CancellationToken ct) => next();
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var reg = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueServiceCollectionExtensions.g.cs");
        var text = reg.SourceText.ToString();

        int outerIdx = text.IndexOf("OuterB<global::GetUser", System.StringComparison.Ordinal);
        int innerIdx = text.IndexOf("InnerB<global::GetUser", System.StringComparison.Ordinal);

        Assert.True(outerIdx >= 0, "OuterB closed construction must be emitted");
        Assert.True(innerIdx >= 0, "InnerB closed construction must be emitted");
        // Lower [BehaviorOrder] = outermost = emitted first in the IReadOnlyList factory.
        Assert.True(outerIdx < innerIdx, "OuterB (order 0) must precede InnerB (order 10)");
    }

    // ── Phase 4.2.1: ROGUE007 is NOT implemented (PD-17) ──────────────────────────────

    [Fact]
    public void NoEmittedSource_ReferencesRogue007()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class P : IRequest<string> { }
public class PHandler : IRequestHandler<P, string>
{
    public ValueTask<string> Handle(P request, CancellationToken ct) => ValueTask.FromResult(""x"");
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();
        foreach (var s in sources)
        {
            Assert.DoesNotContain("ROGUE007", s.SourceText.ToString());
        }
    }

    // ── NFR-SEC-1 / NFR-PERF-3: code-shape gate ──────────────────────────────────────

    [Fact]
    public void AllEmittedSources_ContainNoReflectionEmitApis()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
public class Q1 : IRequest<int> { }
public class Q1Handler : IRequestHandler<Q1, int>
{
    public ValueTask<int> Handle(Q1 r, CancellationToken ct) => ValueTask.FromResult(1);
}
public class LogB<TReq, TRes> : IPipelineBehavior<TReq, TRes> where TReq : notnull
{
    public ValueTask<TRes> Handle(TReq req, RequestHandlerDelegate<TRes> next, CancellationToken ct) => next();
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var sources = result.Results.SelectMany(r => r.GeneratedSources).ToList();

        foreach (var s in sources)
        {
            var text = s.SourceText.ToString();
            Assert.DoesNotContain("MakeGenericMethod", text);
            Assert.DoesNotContain("Activator.CreateInstance", text);
            Assert.DoesNotContain("Assembly.GetTypes", text);
            Assert.DoesNotContain("AppDomain.GetAssemblies", text);
            Assert.DoesNotContain("Expression.Compile", text);
        }
    }

    [Fact]
    public void AllEmittedSources_UseGlobalQualifiedNames()
    {
        const string source = @"
using SkathIO.Rogue;
using System.Threading;
using System.Threading.Tasks;
public class Query : IRequest<string> { }
public class QueryHandler : IRequestHandler<Query, string>
{
    public ValueTask<string> Handle(Query request, CancellationToken ct) => ValueTask.FromResult(""result"");
}";
        var result = GeneratorTestHelper.RunGeneratorAndAssertClean(source);
        var dispatcher = result.Results.SelectMany(r => r.GeneratedSources)
            .First(s => s.HintName == "RogueDispatcher.g.cs");
        var text = dispatcher.SourceText.ToString();

        // The handler interface reference must use global:: prefix
        Assert.Contains("global::SkathIO.Rogue.IRequestHandler<", text);
        Assert.Contains("global::SkathIO.Rogue.PipelineExecutor", text);
        Assert.Contains("global::SkathIO.Rogue.Unit", text);
    }
}
